/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_SOURCE_H
#define PHP_SOURCE_H

extern zend_module_entry Source_module_entry;
#define phpext_Source_ptr &Source_module_entry

#ifdef PHP_WIN32
# define PHP_SOURCE_API __declspec(dllexport)
#else
# define PHP_SOURCE_API
#endif

ZEND_NAMED_FUNCTION(_wrap_add_button);
ZEND_NAMED_FUNCTION(_wrap_add_check_button);
ZEND_NAMED_FUNCTION(_wrap_add_entry);
ZEND_NAMED_FUNCTION(_wrap_show_message_box);
ZEND_NAMED_FUNCTION(_wrap_add_menu_bar);
ZEND_NAMED_FUNCTION(_wrap_add_radio);
ZEND_NAMED_FUNCTION(_wrap_add_link_button);
ZEND_NAMED_FUNCTION(_wrap_add_switch);
ZEND_NAMED_FUNCTION(_wrap_add_label);
ZEND_NAMED_FUNCTION(_wrap_add_image);
ZEND_NAMED_FUNCTION(_wrap_start);
PHP_MINIT_FUNCTION(Source);

#endif /* PHP_SOURCE_H */
